"""factory: left-right auto-adjacency, blocked links

Revision ID: 0b796fa7a561
Revises: 22639cb48664
Create Date: 2026-08-04 04:11:10.402730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b796fa7a561'
down_revision: Union[str, None] = '22639cb48664'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocked_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grid_id', sa.Integer(), nullable=False),
    sa.Column('source_machine_id', sa.Integer(), nullable=False),
    sa.Column('target_machine_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['grid_id'], ['factory_grids.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_machine_id'], ['machines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_machine_id'], ['machines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_machine_id', 'target_machine_id', name='uq_blocked_links_pair')
    )
    op.create_index(op.f('ix_blocked_links_grid_id'), 'blocked_links', ['grid_id'], unique=False)
    op.create_index(op.f('ix_blocked_links_source_machine_id'), 'blocked_links', ['source_machine_id'], unique=False)
    op.create_index(op.f('ix_blocked_links_target_machine_id'), 'blocked_links', ['target_machine_id'], unique=False)
    op.drop_index('ix_machine_connections_grid_id', table_name='machine_connections')
    op.drop_table('machine_connections')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machine_connections',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('grid_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('source_machine_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('target_machine_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['grid_id'], ['factory_grids.id'], name='machine_connections_grid_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_machine_id'], ['machines.id'], name='machine_connections_source_machine_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_machine_id'], ['machines.id'], name='machine_connections_target_machine_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='machine_connections_pkey'),
    sa.UniqueConstraint('source_machine_id', name='uq_machine_connections_source'),
    sa.UniqueConstraint('target_machine_id', name='uq_machine_connections_target')
    )
    op.create_index('ix_machine_connections_grid_id', 'machine_connections', ['grid_id'], unique=False)
    op.drop_index(op.f('ix_blocked_links_target_machine_id'), table_name='blocked_links')
    op.drop_index(op.f('ix_blocked_links_source_machine_id'), table_name='blocked_links')
    op.drop_index(op.f('ix_blocked_links_grid_id'), table_name='blocked_links')
    op.drop_table('blocked_links')
    # ### end Alembic commands ###
