"""factory: grids, machines, connections

Revision ID: 22639cb48664
Revises: 1d7ccfd2ceda
Create Date: 2026-08-02 00:37:14.357685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22639cb48664'
down_revision: Union[str, None] = '1d7ccfd2ceda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factory_grids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('slot_index', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('last_settled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'slot_index', name='uq_factory_grids_user_slot')
    )
    op.create_index(op.f('ix_factory_grids_user_id'), 'factory_grids', ['user_id'], unique=False)
    op.create_table('machine_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('icon', sa.String(length=8), nullable=False),
    sa.Column('output_resource_id', sa.Integer(), nullable=False),
    sa.Column('output_amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['output_resource_id'], ['resource_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machine_definitions_key'), 'machine_definitions', ['key'], unique=True)
    op.create_table('machine_definition_inputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_definition_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['machine_definition_id'], ['machine_definitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resource_definitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('machine_definition_id', 'resource_id', name='uq_machine_definition_inputs')
    )
    op.create_index(op.f('ix_machine_definition_inputs_machine_definition_id'), 'machine_definition_inputs', ['machine_definition_id'], unique=False)
    op.create_table('machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('grid_id', sa.Integer(), nullable=False),
    sa.Column('machine_definition_id', sa.Integer(), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['grid_id'], ['factory_grids.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['machine_definition_id'], ['machine_definitions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machines_grid_id'), 'machines', ['grid_id'], unique=False)
    op.create_index(op.f('ix_machines_user_id'), 'machines', ['user_id'], unique=False)
    op.create_table('machine_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grid_id', sa.Integer(), nullable=False),
    sa.Column('source_machine_id', sa.Integer(), nullable=False),
    sa.Column('target_machine_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['grid_id'], ['factory_grids.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_machine_id'], ['machines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_machine_id'], ['machines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_machine_id', name='uq_machine_connections_source'),
    sa.UniqueConstraint('target_machine_id', name='uq_machine_connections_target')
    )
    op.create_index(op.f('ix_machine_connections_grid_id'), 'machine_connections', ['grid_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_machine_connections_grid_id'), table_name='machine_connections')
    op.drop_table('machine_connections')
    op.drop_index(op.f('ix_machines_user_id'), table_name='machines')
    op.drop_index(op.f('ix_machines_grid_id'), table_name='machines')
    op.drop_table('machines')
    op.drop_index(op.f('ix_machine_definition_inputs_machine_definition_id'), table_name='machine_definition_inputs')
    op.drop_table('machine_definition_inputs')
    op.drop_index(op.f('ix_machine_definitions_key'), table_name='machine_definitions')
    op.drop_table('machine_definitions')
    op.drop_index(op.f('ix_factory_grids_user_id'), table_name='factory_grids')
    op.drop_table('factory_grids')
    # ### end Alembic commands ###
