"""factory: independent machines, no grid

Revision ID: e6edaa055ac5
Revises: 0b796fa7a561
Create Date: 2026-08-04 05:01:20.303597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e6edaa055ac5'
down_revision: Union[str, None] = '0b796fa7a561'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Reordered from the autogenerated version: dependents (blocked_links,
    # machines.grid_id) must be dropped before factory_grids itself, or
    # Postgres refuses with DependentObjectsStillExist.
    op.drop_index('ix_blocked_links_grid_id', table_name='blocked_links')
    op.drop_index('ix_blocked_links_source_machine_id', table_name='blocked_links')
    op.drop_index('ix_blocked_links_target_machine_id', table_name='blocked_links')
    op.drop_table('blocked_links')
    op.add_column('machines', sa.Column('active', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('machines', sa.Column('last_settled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index('ix_machines_grid_id', table_name='machines')
    op.drop_constraint('machines_grid_id_fkey', 'machines', type_='foreignkey')
    op.drop_column('machines', 'grid_id')
    op.drop_column('machines', 'x')
    op.drop_column('machines', 'y')
    op.drop_index('ix_factory_grids_user_id', table_name='factory_grids')
    op.drop_table('factory_grids')
    # ### end Alembic commands ###


def downgrade() -> None:
    # Reordered from the autogenerated version: factory_grids must exist
    # before anything creates a foreign key to it.
    op.create_table('factory_grids',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('slot_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('width', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('height', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_settled_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='factory_grids_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='factory_grids_pkey'),
    sa.UniqueConstraint('user_id', 'slot_index', name='uq_factory_grids_user_slot')
    )
    op.create_index('ix_factory_grids_user_id', 'factory_grids', ['user_id'], unique=False)

    op.add_column('machines', sa.Column('y', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('machines', sa.Column('x', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('machines', sa.Column('grid_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('machines_grid_id_fkey', 'machines', 'factory_grids', ['grid_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_machines_grid_id', 'machines', ['grid_id'], unique=False)
    op.drop_column('machines', 'last_settled_at')
    op.drop_column('machines', 'active')

    op.create_table('blocked_links',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('grid_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('source_machine_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('target_machine_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['grid_id'], ['factory_grids.id'], name='blocked_links_grid_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_machine_id'], ['machines.id'], name='blocked_links_source_machine_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_machine_id'], ['machines.id'], name='blocked_links_target_machine_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='blocked_links_pkey'),
    sa.UniqueConstraint('source_machine_id', 'target_machine_id', name='uq_blocked_links_pair')
    )
    op.create_index('ix_blocked_links_target_machine_id', 'blocked_links', ['target_machine_id'], unique=False)
    op.create_index('ix_blocked_links_source_machine_id', 'blocked_links', ['source_machine_id'], unique=False)
    op.create_index('ix_blocked_links_grid_id', 'blocked_links', ['grid_id'], unique=False)
    # ### end Alembic commands ###
